FROM thinxcloud/mosquitto

LABEL name="thinxcloud/mosquitto" version="1.4.8292"

# for early testing
RUN apt install -y mosquitto-clients

# mock directory structure for mosquitto data
COPY ./test/mosquitto /mosquitto
COPY ./test/mosquitto/mosquitto.conf /etc/mosquitto/mosquitto.conf

# this must happen in the run-script!!! othervise env-var can not be externalized; happens only in test
RUN mkdir -p /mqtt/auth && \
    PASS=$(/mosquitto/pw -h bcrypt -c 10 -p mosquitto) && \
    echo "thinx:${PASS}" > /mqtt/auth/thinx.pw && \
    echo "Written thinx:${PASS} to /mqtt/auth/thinx.pw" && \
    cat /mqtt/auth/thinx.pw

COPY ./test/mosquitto/auth/thinx.acl /mqtt/auth/thinx.acl