FROM thinxcloud/mosquitto

LABEL name="thinxcloud/mosquitto" version="1.4.8292"

# for early testing
RUN apt install -y mosquitto-clients

# mock directory structure for mosquitto data
COPY ./test/mosquitto /mosquitto
COPY ./test/mosquitto/mosquitto.conf /etc/mosquitto/mosquitto.conf

# this must happen in the run-script!!! othervise env-var can not be externalized; happens only in test
RUN PASS=$(/mosquitto/pw -h bcrypt -c 10 -p mosquitto) && \
    echo "thinx:${PASS}" > /mosquitto/auth/thinx.pw && \
    echo "Written thinx:${PASS} to /mosquitto/auth/thinx.pw"