// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: auth.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Plain text password.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// The client connection's id.
	Clientid      string `protobuf:"bytes,3,opt,name=clientid,proto3" json:"clientid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetUserRequest) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

type GetSuperuserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuperuserRequest) Reset() {
	*x = GetSuperuserRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuperuserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuperuserRequest) ProtoMessage() {}

func (x *GetSuperuserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuperuserRequest.ProtoReflect.Descriptor instead.
func (*GetSuperuserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetSuperuserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CheckAclRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Topic to be checked for.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// The client connection's id.
	Clientid string `protobuf:"bytes,3,opt,name=clientid,proto3" json:"clientid,omitempty"`
	// Topic access.
	Acc           int32 `protobuf:"varint,4,opt,name=acc,proto3" json:"acc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAclRequest) Reset() {
	*x = CheckAclRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAclRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAclRequest) ProtoMessage() {}

func (x *CheckAclRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAclRequest.ProtoReflect.Descriptor instead.
func (*CheckAclRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAclRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CheckAclRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CheckAclRequest) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

func (x *CheckAclRequest) GetAcc() int32 {
	if x != nil {
		return x.Acc
	}
	return 0
}

type AuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the user is authorized/authenticated.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type NameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the gRPC backend.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"d\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bclientid\x18\x03 \x01(\tR\bclientid\"1\n" +
	"\x13GetSuperuserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"q\n" +
	"\x0fCheckAclRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1a\n" +
	"\bclientid\x18\x03 \x01(\tR\bclientid\x12\x10\n" +
	"\x03acc\x18\x04 \x01(\x05R\x03acc\"\x1e\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xb1\x02\n" +
	"\vAuthService\x125\n" +
	"\aGetUser\x12\x14.grpc.GetUserRequest\x1a\x12.grpc.AuthResponse\"\x00\x12?\n" +
	"\fGetSuperuser\x12\x19.grpc.GetSuperuserRequest\x1a\x12.grpc.AuthResponse\"\x00\x127\n" +
	"\bCheckAcl\x12\x15.grpc.CheckAclRequest\x1a\x12.grpc.AuthResponse\"\x00\x127\n" +
	"\aGetName\x12\x16.google.protobuf.Empty\x1a\x12.grpc.NameResponse\"\x00\x128\n" +
	"\x04Halt\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B0Z.github.com/iegomez/mosquitto-go-auth/grpc;grpcb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_auth_proto_goTypes = []any{
	(*GetUserRequest)(nil),      // 0: grpc.GetUserRequest
	(*GetSuperuserRequest)(nil), // 1: grpc.GetSuperuserRequest
	(*CheckAclRequest)(nil),     // 2: grpc.CheckAclRequest
	(*AuthResponse)(nil),        // 3: grpc.AuthResponse
	(*NameResponse)(nil),        // 4: grpc.NameResponse
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: grpc.AuthService.GetUser:input_type -> grpc.GetUserRequest
	1, // 1: grpc.AuthService.GetSuperuser:input_type -> grpc.GetSuperuserRequest
	2, // 2: grpc.AuthService.CheckAcl:input_type -> grpc.CheckAclRequest
	5, // 3: grpc.AuthService.GetName:input_type -> google.protobuf.Empty
	5, // 4: grpc.AuthService.Halt:input_type -> google.protobuf.Empty
	3, // 5: grpc.AuthService.GetUser:output_type -> grpc.AuthResponse
	3, // 6: grpc.AuthService.GetSuperuser:output_type -> grpc.AuthResponse
	3, // 7: grpc.AuthService.CheckAcl:output_type -> grpc.AuthResponse
	4, // 8: grpc.AuthService.GetName:output_type -> grpc.NameResponse
	5, // 9: grpc.AuthService.Halt:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
